spring:
  application:
    name: organizationservice
    profiles:
      active: default
    datasource:
      url: jdbc:mysql://localhost:3306/eagereyes
      username: root
      password:                # for build and test, we use username:password(root,"") in the configure.
      driverClassName: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      continueOnError: true
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      jpa:
        hibernate:
          ddl-auto: update
        database-platform: org.hibernate.dialect.MySQLDialect
    ribbon:
      ConnectTimeout: 60000
      ReadTimeout: 60000
    hystrix:
      command:
        default:
          execution:
            isolation:
              thread:
                timeoutInMillisecon